# Generated by Django 4.1.1 on 2022-09-22 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
