# Generated by Django 4.1.1 on 2022-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_customuser_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.ManyToManyField(related_name='posts', to='post.post'),
        ),
    ]
