# Generated by Django 4.1.1 on 2022-09-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_commentpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='comment_user',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
