# Generated by Django 4.1.1 on 2022-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_course_student_course_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
