# Generated by Django 4.1.1 on 2022-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='final_grade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
