# Generated by Django 4.1.1 on 2022-09-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgge_url',
            new_name='image_url',
        ),
    ]
